### ISSUE TITLE
Dummy Options with Disk/Question Mark

### ISSUE THREAD

**Issue by CJ32001** [chadvandy/van_mct#375]
Recommend removing campaign disk / question mark from dummy options. 
![Screenshot 2023-02-19 105417](https://user-images.githubusercontent.com/117957083/219965953-1b352261-238c-4f71-ae43-5710f2fd3eb3.png)

**Comment by chadvandy** [comment]
use section:set_description(), dummy options aren't really supported anymore and should be considered legacy until I fully deprecate them

**Comment by chadvandy** [comment]
ended up fixing this anyway

**Comment by CJ32001** [comment]
Nice. Well, I promise I'll get around to using section:set_description() instead one of these days
