### ISSUE TITLE
Display a reason for why an option cannot be changed.

### ISSUE THREAD

**Issue by DrunkFlamingo** [chadvandy/van_mct#85]
To provide explainations to users on why a option is currently set as read only.

Useful when options have to be locked in specific contexts, example usecases:
- This option cannot be changed while the exchange panel is open
- This option cannot be changed when the rifts are open.

**Comment by chadvandy** [comment]
will be resupported once #92 is fixed

**Comment by chadvandy** [comment]
works - mct_option:set_locked(true, "This option can't be changed while the exchange panel is open"), followed by mct_option:set_locked(false)
