### ISSUE TITLE
Add confirmation popups for specific options.

### ISSUE THREAD

**Issue by DrunkFlamingo** [chadvandy/van_mct#86]
Some options get asked for by users a lot but are potentially unstable if used in a stupid way. It would be nice to be able to force people to click through a disclaimer in certain situations.

A command which allows us to specify that a certain option requires a confirmation popup, something like:
`enable_option:ask_if_theyre_fucking_sure("loc_key", function(mct) return __game_mode == __lib_type_campaign end)`

Would work.

**Comment by chadvandy** [comment]
note for me: 

mct_option:add_confirmation_popup(function() if __game_mode == __lib_type_campaign then return false, "The text to display on the popup" end return true end)

**Comment by chadvandy** [comment]
```
mct_option:add_confirmation_popup(
    function(new_val)
        if new_val == false then
            return true, "Are you sure you want to change this Global Unlocked Checkbox to false?"
        end

        return false
    end
)
```
